version: "3"
services:
  app:
    build:
      context: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}
    command: ./manage.py runserver 0:${PORT}
    depends_on:
      - postgres
      - redis

  celery:
    build:
      context: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    command: watchmedo auto-restart 
      --directory=./ --pattern=*.py --recursive --ignore-patterns=./env/* -- 
      celery worker -A capritools -B -c 2
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:12.3
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=capritools2
      - POSTGRES_PASSWORD=FygY3YYt

  redis:
    image: redis:5.0
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
