version: "3"
services:
  app:
    image: skyride/capritools-2:1.3.1
    restart: always
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - redis

  celery:
    image: skyride/capritools-2:1.3.1
    restart: always
    env_file:
      - .env
    command: celery worker -A capritools -B -c ${CELERY_WORKERS}
    depends_on:
      - redis

  redis:
    image: redis:5.0
    volumes:
      - redisdata:/data

volumes:
  redisdata:
